# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bf8b791807243069753790684d48d5eccef80dc0efadcb91c9308326d8f79b0a42a625ff61a42347a8948f59f55d717099c236f6d7662e1b452d468bde3e35a

test:
  secret_key_base: 0b99ae646682a7fefd61b8372632adee0e3ced2c1b8a32e21f7e516d6aff268129621bd5c3c7a3f4d414c677e93a85b6fa04134d666c21f160f8acd992dd41cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
